# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jdamgov/CaloX/sim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jdamgov/CaloX/sim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jdamgov/CaloX/sim/CMakeFiles /home/jdamgov/CaloX/sim/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jdamgov/CaloX/sim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named exampleB4b

# Build rule for target.
exampleB4b: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exampleB4b
.PHONY : exampleB4b

# fast build rule for target.
exampleB4b/fast:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/build
.PHONY : exampleB4b/fast

exampleB4b.o: exampleB4b.cc.o

.PHONY : exampleB4b.o

# target to build an object file
exampleB4b.cc.o:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/exampleB4b.cc.o
.PHONY : exampleB4b.cc.o

exampleB4b.i: exampleB4b.cc.i

.PHONY : exampleB4b.i

# target to preprocess a source file
exampleB4b.cc.i:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/exampleB4b.cc.i
.PHONY : exampleB4b.cc.i

exampleB4b.s: exampleB4b.cc.s

.PHONY : exampleB4b.s

# target to generate assembly for a file
exampleB4b.cc.s:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/exampleB4b.cc.s
.PHONY : exampleB4b.cc.s

src/._B4xTrackingAction.o: src/._B4xTrackingAction.cc.o

.PHONY : src/._B4xTrackingAction.o

# target to build an object file
src/._B4xTrackingAction.cc.o:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/._B4xTrackingAction.cc.o
.PHONY : src/._B4xTrackingAction.cc.o

src/._B4xTrackingAction.i: src/._B4xTrackingAction.cc.i

.PHONY : src/._B4xTrackingAction.i

# target to preprocess a source file
src/._B4xTrackingAction.cc.i:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/._B4xTrackingAction.cc.i
.PHONY : src/._B4xTrackingAction.cc.i

src/._B4xTrackingAction.s: src/._B4xTrackingAction.cc.s

.PHONY : src/._B4xTrackingAction.s

# target to generate assembly for a file
src/._B4xTrackingAction.cc.s:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/._B4xTrackingAction.cc.s
.PHONY : src/._B4xTrackingAction.cc.s

src/B4DetectorConstruction.o: src/B4DetectorConstruction.cc.o

.PHONY : src/B4DetectorConstruction.o

# target to build an object file
src/B4DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4DetectorConstruction.cc.o
.PHONY : src/B4DetectorConstruction.cc.o

src/B4DetectorConstruction.i: src/B4DetectorConstruction.cc.i

.PHONY : src/B4DetectorConstruction.i

# target to preprocess a source file
src/B4DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4DetectorConstruction.cc.i
.PHONY : src/B4DetectorConstruction.cc.i

src/B4DetectorConstruction.s: src/B4DetectorConstruction.cc.s

.PHONY : src/B4DetectorConstruction.s

# target to generate assembly for a file
src/B4DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4DetectorConstruction.cc.s
.PHONY : src/B4DetectorConstruction.cc.s

src/B4PrimaryGeneratorAction.o: src/B4PrimaryGeneratorAction.cc.o

.PHONY : src/B4PrimaryGeneratorAction.o

# target to build an object file
src/B4PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4PrimaryGeneratorAction.cc.o
.PHONY : src/B4PrimaryGeneratorAction.cc.o

src/B4PrimaryGeneratorAction.i: src/B4PrimaryGeneratorAction.cc.i

.PHONY : src/B4PrimaryGeneratorAction.i

# target to preprocess a source file
src/B4PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4PrimaryGeneratorAction.cc.i
.PHONY : src/B4PrimaryGeneratorAction.cc.i

src/B4PrimaryGeneratorAction.s: src/B4PrimaryGeneratorAction.cc.s

.PHONY : src/B4PrimaryGeneratorAction.s

# target to generate assembly for a file
src/B4PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4PrimaryGeneratorAction.cc.s
.PHONY : src/B4PrimaryGeneratorAction.cc.s

src/B4bActionInitialization.o: src/B4bActionInitialization.cc.o

.PHONY : src/B4bActionInitialization.o

# target to build an object file
src/B4bActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4bActionInitialization.cc.o
.PHONY : src/B4bActionInitialization.cc.o

src/B4bActionInitialization.i: src/B4bActionInitialization.cc.i

.PHONY : src/B4bActionInitialization.i

# target to preprocess a source file
src/B4bActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4bActionInitialization.cc.i
.PHONY : src/B4bActionInitialization.cc.i

src/B4bActionInitialization.s: src/B4bActionInitialization.cc.s

.PHONY : src/B4bActionInitialization.s

# target to generate assembly for a file
src/B4bActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4bActionInitialization.cc.s
.PHONY : src/B4bActionInitialization.cc.s

src/B4bEventAction.o: src/B4bEventAction.cc.o

.PHONY : src/B4bEventAction.o

# target to build an object file
src/B4bEventAction.cc.o:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4bEventAction.cc.o
.PHONY : src/B4bEventAction.cc.o

src/B4bEventAction.i: src/B4bEventAction.cc.i

.PHONY : src/B4bEventAction.i

# target to preprocess a source file
src/B4bEventAction.cc.i:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4bEventAction.cc.i
.PHONY : src/B4bEventAction.cc.i

src/B4bEventAction.s: src/B4bEventAction.cc.s

.PHONY : src/B4bEventAction.s

# target to generate assembly for a file
src/B4bEventAction.cc.s:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4bEventAction.cc.s
.PHONY : src/B4bEventAction.cc.s

src/B4bRunAction.o: src/B4bRunAction.cc.o

.PHONY : src/B4bRunAction.o

# target to build an object file
src/B4bRunAction.cc.o:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4bRunAction.cc.o
.PHONY : src/B4bRunAction.cc.o

src/B4bRunAction.i: src/B4bRunAction.cc.i

.PHONY : src/B4bRunAction.i

# target to preprocess a source file
src/B4bRunAction.cc.i:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4bRunAction.cc.i
.PHONY : src/B4bRunAction.cc.i

src/B4bRunAction.s: src/B4bRunAction.cc.s

.PHONY : src/B4bRunAction.s

# target to generate assembly for a file
src/B4bRunAction.cc.s:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4bRunAction.cc.s
.PHONY : src/B4bRunAction.cc.s

src/B4bRunData.o: src/B4bRunData.cc.o

.PHONY : src/B4bRunData.o

# target to build an object file
src/B4bRunData.cc.o:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4bRunData.cc.o
.PHONY : src/B4bRunData.cc.o

src/B4bRunData.i: src/B4bRunData.cc.i

.PHONY : src/B4bRunData.i

# target to preprocess a source file
src/B4bRunData.cc.i:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4bRunData.cc.i
.PHONY : src/B4bRunData.cc.i

src/B4bRunData.s: src/B4bRunData.cc.s

.PHONY : src/B4bRunData.s

# target to generate assembly for a file
src/B4bRunData.cc.s:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4bRunData.cc.s
.PHONY : src/B4bRunData.cc.s

src/B4bSteppingAction.o: src/B4bSteppingAction.cc.o

.PHONY : src/B4bSteppingAction.o

# target to build an object file
src/B4bSteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4bSteppingAction.cc.o
.PHONY : src/B4bSteppingAction.cc.o

src/B4bSteppingAction.i: src/B4bSteppingAction.cc.i

.PHONY : src/B4bSteppingAction.i

# target to preprocess a source file
src/B4bSteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4bSteppingAction.cc.i
.PHONY : src/B4bSteppingAction.cc.i

src/B4bSteppingAction.s: src/B4bSteppingAction.cc.s

.PHONY : src/B4bSteppingAction.s

# target to generate assembly for a file
src/B4bSteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4bSteppingAction.cc.s
.PHONY : src/B4bSteppingAction.cc.s

src/B4xTrackingAction.o: src/B4xTrackingAction.cc.o

.PHONY : src/B4xTrackingAction.o

# target to build an object file
src/B4xTrackingAction.cc.o:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4xTrackingAction.cc.o
.PHONY : src/B4xTrackingAction.cc.o

src/B4xTrackingAction.i: src/B4xTrackingAction.cc.i

.PHONY : src/B4xTrackingAction.i

# target to preprocess a source file
src/B4xTrackingAction.cc.i:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4xTrackingAction.cc.i
.PHONY : src/B4xTrackingAction.cc.i

src/B4xTrackingAction.s: src/B4xTrackingAction.cc.s

.PHONY : src/B4xTrackingAction.s

# target to generate assembly for a file
src/B4xTrackingAction.cc.s:
	$(MAKE) -f CMakeFiles/exampleB4b.dir/build.make CMakeFiles/exampleB4b.dir/src/B4xTrackingAction.cc.s
.PHONY : src/B4xTrackingAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... exampleB4b"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... exampleB4b.o"
	@echo "... exampleB4b.i"
	@echo "... exampleB4b.s"
	@echo "... src/._B4xTrackingAction.o"
	@echo "... src/._B4xTrackingAction.i"
	@echo "... src/._B4xTrackingAction.s"
	@echo "... src/B4DetectorConstruction.o"
	@echo "... src/B4DetectorConstruction.i"
	@echo "... src/B4DetectorConstruction.s"
	@echo "... src/B4PrimaryGeneratorAction.o"
	@echo "... src/B4PrimaryGeneratorAction.i"
	@echo "... src/B4PrimaryGeneratorAction.s"
	@echo "... src/B4bActionInitialization.o"
	@echo "... src/B4bActionInitialization.i"
	@echo "... src/B4bActionInitialization.s"
	@echo "... src/B4bEventAction.o"
	@echo "... src/B4bEventAction.i"
	@echo "... src/B4bEventAction.s"
	@echo "... src/B4bRunAction.o"
	@echo "... src/B4bRunAction.i"
	@echo "... src/B4bRunAction.s"
	@echo "... src/B4bRunData.o"
	@echo "... src/B4bRunData.i"
	@echo "... src/B4bRunData.s"
	@echo "... src/B4bSteppingAction.o"
	@echo "... src/B4bSteppingAction.i"
	@echo "... src/B4bSteppingAction.s"
	@echo "... src/B4xTrackingAction.o"
	@echo "... src/B4xTrackingAction.i"
	@echo "... src/B4xTrackingAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

